export const FormClass = 'finalize-offer-form'
export const OfferInputName = 'offer'
export const OfferIdInputName = 'offer-id'
export const AddressInputName = 'address'
export const PerpetualAddressInputName = 'perpetual-address'
