export const FormId = {
  Form: 'fi-form',
  FormTitle: 'fi-form-title',
  AssetSelect: 'fi-asset-select',
  AssetAmountInput: 'fi-asset-amount-input',
  AmountErrorView: 'fi-amount-error-view',
  AssetMaxButton: 'fi-asset-max-button',
  AssetBalanceView: 'fi-asset-balance-view',
  AssetIconView: 'fi-asset-icon-view',
  AssetSymbolView: 'fi-asset-symbol-view',
  PriceSection: 'fi-price-section',
  PriceInput: 'fi-price-input',
  SuggestedPriceView: 'fi-suggested-price-view',
  SuggestedPriceButton: 'fi-suggested-price-button',
  TotalSection: 'fi-total-section',
  TotalInput: 'fi-total-input',
  SubmitButton: 'fi-submit-button',
  ExitButton: 'fi-exit-button',
  BuyButton: 'fi-buy-button',
  SellButton: 'fi-sell-button',
  InfoSection: 'fi-info-section',
}
